export const FETCH_QUIZES_START = 'FETCH_QUIZES_START'
export const FETCH_QUIZES_SUCCESS = 'FETCH_QUIZES_SUCCESS'
export const FETCH_QUIZES_ERROR = 'FETCH_QUIZES_ERROR'

export const FETCH_QUIZ_START = 'FETCH_QUIZ_START'
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS'
export const FETCH_QUIZ_ERROR = 'FETCH_QUIZ_ERROR'

export const QUIZ_SET_STATE = 'QUIZ_SET_STATE'
export const QUIZ_FINISHED = 'QUIZ_FINISHED'
export const QUIZ_NEXT_QUESTION = 'QUIZ_NEXT_QUESTION'
export const RETRY_QUIZ = 'RETRY_QUIZ'

export const CREATE_QUIZ_QUISTION = 'CREATE_QUIZ_QUISTION'
export const RESET_QUIZ_CREATION = 'RESET_QUIZ_CREATION'

export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'